version: 2
project_name: network_exporter
dist: artifacts
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    targets:
      - linux_arm
      - linux_arm64
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    main: .
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: network_exporter
archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}.
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - README.md
      - LICENSE.md
      - network_exporter.yml
    wrap_in_directory: false
snapshot:
  version_template: SNAPSHOT-{{ .Commit }}
nfpms:
  - vendor: Sebastian YEPES
    homepage: "https://github.com/syepes/network_exporter"
    maintainer: Sebastian YEPES
    description: "Network Prometheus Exporter"
    license: Apache 2.0 License
    formats:
      - deb
      - rpm
    bindir: /usr/bin
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
